version: '3'

services:
  mysql:
    image: mysql
    container_name: cod3r-graphql-challenge_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "challenge"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

volumes:
  mysql-volume:
    driver: local

networks:
  app-network:
    driver: bridge
